#ifndef GALAXY_ERROR_H
#define GALAXY_ERROR_H
typedef enum {
    // generic
    GALAXY_OK,
    GALAXY_UNKNOWN,
 
    // firmware
    GALAXY_FIRMWARE_PATH_INVALID,
    GALAXY_FIRMWARE_CHARGEN_MISSING,
    GALAXY_FIRMWARE_CHARGEN_INVALID,
    GALAXY_FIRMWARE_CHARGEN_READ_FAILURE,
    GALAXY_FIRMWARE_ROM1_MISSING,
    GALAXY_FIRMWARE_ROM1_INVALID,
    GALAXY_FIRMWARE_ROM1_READ_FAILURE,
    GALAXY_FIRMWARE_ROM2_MISSING,
    GALAXY_FIRMWARE_ROM2_INVALID,
    GALAXY_FIRMWARE_ROM2_READ_FAILURE,

    // chargen
    GALAXY_CHARGEN_PIXEL_FORMAT_INVALID,

    // colorgen
    GALAXY_COLORGEN_PIXEL_FORMAT_INVALID,

    // draw
    GALAXY_DRAW_PIXEL_FORMAT_INVALID,

    // clear screen
    GALAXY_CLEAR_SCREEN_PIXEL_FORMAT_INVALID,

    // load/save
    GALAXY_STATE_LOAD_FILE_FAILED,
    GALAXY_STATE_SAVE_FILE_FAILED,
    GALAXY_STATE_LOAD_NOT_RECOGNIZED,
} galaxy_error;

#endif
