#ifndef GALAXY_SYSTEM_H_
#define GALAXY_SYSTEM_H_

#define GALAXY_CHARGEN_SIZE  0x0800
#define GALAXY_ROM1_SIZE     0x1000
#define GALAXY_ROM1_START    0x0000
#define GALAXY_ROM2_SIZE     0x1000
#define GALAXY_ROM2_START    0x1000
#define GALAXY_ADDRESS_SPACE 0xffff
#define GALAXY_KEYBOARD_ADDR_START 0x2000
#define GALAXY_KEYBOARD_ADDR_END   0x2800
#define GALAXY_SCREEN_ADDR_START   0x2800
#define GALAXY_SCREEN_ADDR_END     0x2A00
#define GALAXY_RAM_ADDR_START      0x2000
#define GALAXY_FREE_RAM_ADDR_START 0x2800
#define GALAXY_RAM_ADDR_END        0x4000
#define GALAXY_RAM_SIZE            (GALAXY_RAM_ADDR_END-GALAXY_RAM_ADDR_START)
#define GALAXY_CHARMAP_SIZE        256

#define GALAXY_OFFSET_HORIZONTAL_POSITION 0x2BA8

#define GALAXY_FONT_WIDTH  8
#define GALAXY_FONT_HEIGHT 13
#define GALAXY_CHAR_PIXEL_COUNT (GALAXY_FONT_WIDTH*GALAXY_FONT_HEIGHT)
#define GALAXY_FONT_COUNT  128 // refers to the number of possible characters

#define GALAXY_HORIZONTAL_CHARS      32
#define GALAXY_VERTICAL_CHARS        16
#define GALAXY_CHAR_COUNT            \
    (GALAXY_HORIZONTAL_CHARS*GALAXY_VERTICAL_CHARS)

#define GALAXY_HORIZONTAL_RESOLUTION \
    (GALAXY_HORIZONTAL_CHARS*GALAXY_FONT_WIDTH) // 256 pixels
#define GALAXY_VERTICAL_RESOLUTION \
    (GALAXY_VERTICAL_CHARS*GALAXY_FONT_HEIGHT) // 208 pixels
#define GALAXY_PIXEL_COUNT \
    (GALAXY_VERTICAL_RESOLUTION*GALAXY_HORIZONTAL_RESOLUTION)

#define GALAXY_CPU_FREQUENCY 3072000 // 6.144/2 MHz

#define GALAXY_FRAMERATE     50      // because PAL

#define GALAXY_DOS_STATE_SIZE 8268

#define GALAXY_SCREEN_TEST_ENABLE 1

#endif

